services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    environment:
      PORT: ${PORT}
      RELEASE_ID: ${RELEASE_ID_BLUE}
      APP_POOL: blue
    ports:
      - "8081:8080"

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    environment:
      PORT: ${PORT}
      RELEASE_ID: ${RELEASE_ID_GREEN}
      APP_POOL: green
    ports:
      - "8082:8080"

  alert_watcher:
    build:
      context: ./watcher
      dockerfile: Dockerfile
    container_name: alert_watcher
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      ACTIVE_POOL: ${ACTIVE_POOL}
      ERROR_RATE_THRESHOLD: ${ERROR_RATE_THRESHOLD}
      WINDOW_SIZE: ${WINDOW_SIZE}
      ALERT_COOLDOWN_SEC: ${ALERT_COOLDOWN_SEC}
      POLL_INTERVAL: ${POLL_INTERVAL}
      MAINTENANCE_MODE: ${MAINTENANCE_MODE}
      MAINTENANCE_FILE: /app/maintenance/maintenance.flag
      QUIET: ${QUIET}
    volumes:
      - nginx_logs:/var/log/nginx:ro
      - ./watcher/maintenance:/app/maintenance:ro
    depends_on:
      - nginx

volumes:
  nginx_logs:
